[workspace]
authors = ["halterc <chalterbio@gmail.com>"]
channels = ["conda-forge", "bioconda", "pytorch", "nvidia"]
name = "ECODA_paper"
platforms = ["osx-arm64", "linux-64"]
channel-priority = "disabled"

[dependencies]
r-base = "==4.5.2"
python = "==3.11.11"

# ==========================================
# FEATURE 1: The Standalone Python Stack
# ==========================================
[feature.py-standalone.dependencies]
scanpy = "==1.9.6"
anndata = "==0.11.3"


# OS-Specific GPU Handling for Python
# ------------------------------------------
[feature.py-standalone.target.linux-64.dependencies]
pytorch = { version = "*", build = "*cuda*" }
pytorch-cuda = { version = "*" }

# Linux gets CUDA 12 PyPI Wheels
[feature.py-standalone.target.linux-64.pypi-dependencies]
jax = { version = "*", extras = ["cuda12"] }

# macOS gets the standard Conda CPU/MPS build
[feature.py-standalone.target.osx-arm64.dependencies]
jax = "*"
pytorch = "*"

# Fallback for packages only available on PyPI
# ------------------------------------------
[feature.py-standalone.pypi-dependencies]
scHPL = "==1.0.0" # see https://github.com/theislab/scarches/issues/262
pilotpy = "==2.0.15"
scikit-misc = "==0.5.1"
scvi-tools = "==1.2.2.post2"
scarches = "==0.6.1"

# ==========================================
# FEATURE 2: The R and Reticulate Stack
# ==========================================
[feature.r-bridge.dependencies]
# Add your R packages here (e.g., r-seurat = "*")

# ==========================================
# ENVIRONMENTS 
# ==========================================
[environments]
py-tools = ["py-standalone"]
r-tools = ["r-bridge"]