---
title: "Compositional data analysis of the Gong & Sharma et al. dataset"
author: "Christian Halter"
date: "`r format(Sys.Date(),'%e de %B, %Y')`"
output: 
  rmdformats::downcute:
    lightbox: true
    thumbnails: false
    self_contained: true
    gallery: true
    code_folding: show
  pkgdown:
    as_is: true
---

# Load libraries

```{r, include=FALSE, fig.width=16, fig.height=12}
source("functions.R")

library(readxl)
library(scales)

my_seed <- 123
set.seed(my_seed)
```

# Set paths

```{r}
path_root <- getwd()
path_data <- file.path(path_root, "data", "other")
path_plots <- file.path(path_root, "plots")
```

```{r}
df <- data.table::fread(file.path(path_data, "Svensson_sc_database_20250508.txt"), sep = "\t")

# Convert Date to date format
df <- df %>%
  mutate(Date = ymd(Date)) %>%
  mutate(Year = year(Date))


num_cols <- c(
  "Number individuals",
  "Reported cells total",
  "Number of reported cell types or clusters"
)

# Remove commas from numeric columns and convert to numeric
df <- df %>%
  mutate(across(all_of(num_cols), ~as.numeric(gsub(",", "", .))))


df <- df[df$Year >= 2015]

mean_data <- df %>%
  group_by(Year) %>%
  summarise(
    number_individuals = mean(`Number individuals`, na.rm = TRUE),
    mean_cells = mean(`Reported cells total`, na.rm = TRUE),
    mean_cell_types = mean(`Number of reported cell types or clusters`, na.rm = TRUE),
    )


width <- 3
height <- 3

point_size <- 0.5
point_color <- "lightgrey"

ggplot(df, aes(x = Date, y = `Number individuals`)) +
  geom_point(size = point_size, color = point_color) +
  geom_smooth(method = "lm") +
  scale_y_log10(
    breaks = 10^(0:8),
    labels = trans_format("log10", math_format(10^.x))
  ) +
  ylab("Individuals") +
  ggtitle("Individuals per study") +
  theme_classic()
# ggplot(data = mean_data, aes(x = Year, y = number_individuals)) +
#   # geom_point(data = df, aes(x = Year, y = `Reported cells total`), size = 3, alpha = 0.7) +  # Original points
#   geom_point(size = 3) +
#   geom_line() +
#   labs(y = "Number of individuals") +
#   scale_x_continuous(breaks = breaks_pretty()) +
#   # scale_y_continuous(trans='log2', n.breaks = 10) +
#   theme_classic()
ggsave(file.path(path_plots, "literature_datasets_number_individuals.pdf"),
       width = width,
       height = height)


ggplot(df, aes(x = Date, y = `Reported cells total`)) +
  geom_point(size = point_size, color = point_color) +
  geom_smooth(method = "lm") +
  scale_y_log10(
    breaks = 10^(0:8),
    labels = trans_format("log10", math_format(10^.x))
  ) +
  # annotation_logticks() +
  ylab("Cells") +
  ggtitle("Cells per study") +
  theme_classic()
# ggplot(data = mean_data, aes(x = Year, y = mean_cells)) +
#   # geom_point(data = df, aes(x = Year, y = `Reported cells total`), size = 3, alpha = 0.7) +  # Original points
#   geom_point(size = 3) +
#   geom_line() +
#   labs(x = "Year", y = "Number of cells per dataset", title = "Original and Mean Points with Connecting Lines") +
#   scale_x_continuous(breaks = breaks_pretty()) +
#   scale_y_log10(
#     breaks = 10^(0:8),
#     labels = trans_format("log10", math_format(10^.x))
#   ) +
#   theme_classic()
ggsave(file.path(path_plots, "literature_datasets_number_cells_per_dataset.pdf"),
       width = width,
       height = height)


ggplot(df, aes(x = Date, y = `Number of reported cell types or clusters`)) +
  geom_point(size = point_size, color = point_color) +
  geom_smooth(method = "lm") +
  scale_y_log10(
    breaks = 10^(0:8),
    labels = trans_format("log10", math_format(10^.x))
  ) +
  ggtitle("Cell types per study") +
  ylab("Cell types") +
  theme_classic()
# ggplot(data = mean_data, aes(x = Year, y = mean_cell_types)) +
#   # geom_point(data = df, aes(x = Year, y = `Reported cells total`), size = 3, alpha = 0.7) +  # Original points
#   geom_point(size = 3) +
#   geom_line() +
#   labs(x = "Year", y = "Number of cells per dataset", title = "Original and Mean Points with Connecting Lines") +
#   scale_x_continuous(breaks = breaks_pretty()) +
#   scale_y_log10(
#     breaks = 10^(0:8),
#     labels = trans_format("log10", math_format(10^.x))
#   ) +
#   theme_classic()
ggsave(file.path(path_plots, "literature_datasets_number_annotated_cell_types.pdf"),
       width = width,
       height = height)
```

