---
title: "Compositional data analysis of the Gong & Sharma et al. dataset"
author: "Christian Halter"
date: "`r format(Sys.Date(),'%e de %B, %Y')`"
output: 
  rmdformats::downcute:
    lightbox: true
    thumbnails: false
    self_contained: true
    gallery: true
    code_folding: show
  pkgdown:
    as_is: true
---


# Load libraries

```{r, include=FALSE, fig.width=16, fig.height=12}
# renv::init()
# renv::snapshot()

# install.packages("/Users/christianhalter/Desktop/scooter_1.0.0.tar.gz", repos = NULL, type = "source")

library(scooter)
library(tidyverse)
library(plotly)
library(ggplot2)
library(ggpubr)
library(factoextra)
library(compositions)
library(pROC)
library(mclust)
library(rstatix)
source("functions.R")

library(Seurat)
# devtools::install_github('satijalab/seurat-data')
library(SeuratData)
# install.packages("hdf5r")
# remotes::install_github("mojaveazure/seurat-disk")
library(SeuratDisk)

# install.packages("devtools")
# devtools::install_github("GfellerLab/EPIC", build_vignettes=TRUE)
library(EPIC)
# BiocManager::install("MOFA2")
library(reticulate)
library(basilisk)
library("MOFA2")
# BiocManager::install("fgsea")
# BiocManager::install("sva")
# devtools::install_github("kharchenkolab/scITD")
library(scITD)
# install.packages("ncdf4")
library(ncdf4)
library(arrow)

library(dplyr)

my_seed <- 123
set.seed(my_seed)
```

# Set paths

```{r}
ds_name <- "GongSharma_2024_PrePrintTBD"

path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_data <- file.path(path_root, "data")
path_plots <- file.path("~", "Dropbox", "CSI", "PAPERS", "ECODA", "plots")
```


# ---------------------------------------------------------------


## Test on real datasets

```{r}
results_list <- list()
```


### Zhang et al. dataset

```{r}
ds_name <- "ZhangY_2022_34653365"
path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_output <- file.path(path_root, "output")
path_output_samples <- file.path(path_output, "samples")

obj.list <- read_objs(path_output_samples)

# Exclude samples that consist mainly of one cell type as outliers
samples_exclude <- c("Pre_P012_b", "Pre_P013_t")
obj.list <- obj.list[!names(obj.list) %in% samples_exclude]

samples_clearcut <- c()

for (i in names(obj.list)) {
  if (obj.list[[i]]@meta.data$Treatment[1] %in% c("Pre") &
      !(obj.list[[i]]@meta.data$Clinical.efficacy.[1] %in% c("-"))) {
    samples_clearcut <- c(samples_clearcut, i)
  }
}

metacols_to_keep <- c("Sample", "Tissue", "layer1", "layer2")

for (i in samples_clearcut) {
  print(i)
  
  obj <- obj.list[[i]]
  Idents(obj) <- "Sample"
  obj@meta.data <- obj@meta.data[colnames(obj@assays$RNA$counts), metacols_to_keep]

  if (i == samples_clearcut[1]) {
    seurat <- obj
  } else {
    seurat <- merge(seurat, obj)
  }
}

rm(obj.list); gc()

label_condition <- "Tissue"
low_res_ct_col <- "layer1"
hi_res_ct_col <- "layer2"


count_mat <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "Zhang"
results_list[[ds]] <- datrans(count_mat = count_mat, labels = labels, perc_diffs = 0, n_ct_to_select = 0, reps = 20, n_cores = 1,
                                   methods = c(
                                     "counts",
                                     "freq",
                                     "arcsine_sqrt",
                                     "alr_randref",
                                     "alr_mincvref",
                                     "clr"
                                   ))
results_list[[ds]] <- results_list[[ds]] %>%
  group_by(method) %>%
  summarize(silhouette = mean(silhouette),
            modularity = mean(modularity),
            clustering = mean(clustering)) %>%
  ungroup()
results_list[[ds]]$dataset <- ds
```



### Stephenson et al. dataset


```{r}
# Set paths
ds_name <- "MitchelJ_2023_PrePrintTBD"

path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_output <- file.path(path_root, "output")

seurat <- readRDS(file.path(path_output, sprintf("%s_Stephenson_preprocessed.rds", ds_name)))

seurat <- subset(seurat, subset = Site == "Ncl")
seurat <- subset(seurat, subset = Status %in% c("Healthy", "Covid"))
seurat$Days_from_onset <- as.character(seurat$Days_from_onset)
seurat$Days_from_onset[seurat$Days_from_onset == "Healthy"] <- 0
seurat$Days_from_onset <- as.numeric(seurat$Days_from_onset)
seurat <- subset(seurat, subset = Days_from_onset < 10)

seurat$sample_id <- as.character(seurat$sample_id)
samples_exclude <- c("BGCV10_CV0198", "MH8919230")
samples_subset <- unique(seurat$sample_id[!seurat$sample_id %in% samples_exclude])
seurat <- subset(seurat, subset = sample_id %in% samples_subset)


label_condition <- "Status"
low_res_ct_col <- "initial_clustering"
hi_res_ct_col <- "full_clustering"


count_mat <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "Stephenson"
results_list[[ds]] <- datrans(count_mat = count_mat, labels = labels, perc_diffs = 0, n_ct_to_select = 0, reps = 20, n_cores = 1,
                                   methods = c(
                                     "counts",
                                     "freq",
                                     "arcsine_sqrt",
                                     "alr_randref",
                                     "alr_mincvref",
                                     "clr"
                                   ))
results_list[[ds]] <- results_list[[ds]] %>%
  group_by(method) %>%
  summarize(silhouette = mean(silhouette),
            modularity = mean(modularity),
            clustering = mean(clustering)) %>%
  ungroup()
results_list[[ds]]$dataset <- ds
```



### Lee et al. dataset


```{r}
# Set paths
ds_name <- "LeeA_2021_34836966"

path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_output <- file.path(path_root, "output")

seurat <- readRDS(file.path(path_output, sprintf("%sp_tumor_seurat.rds", ds_name)))

label_condition <- "condition"
low_res_ct_col <- "scGate_multi"
hi_res_ct_col <- "functional.cluster"


count_mat <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "Lee"
results_list[[ds]] <- datrans(count_mat = count_mat, labels = labels, perc_diffs = 0, n_ct_to_select = 0, reps = 20, n_cores = 1,
                                   methods = c(
                                     "counts",
                                     "freq",
                                     "arcsine_sqrt",
                                     "alr_randref",
                                     "alr_mincvref",
                                     "clr"
                                   ))
results_list[[ds]] <- results_list[[ds]] %>%
  group_by(method) %>%
  summarize(silhouette = mean(silhouette),
            modularity = mean(modularity),
            clustering = mean(clustering)) %>%
  ungroup()
results_list[[ds]]$dataset <- ds
```


### Gong and Sharma et al. dataset

#### CMV


```{r}
# Set paths
ds_name <- "GongSharma_2024_PrePrintTBD"
path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_output <- file.path(path_root, "output")

seurat <- load_seurat_object("data/gongsharma_all.h5ad")
seurat$Sample <- seurat$specimen.specimenGuid


label_condition <- "subject.cmv"
low_res_ct_col <- "AIFI_L1"
hi_res_ct_col <- "AIFI_L3"

count_mat <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "GongSharma_cmv"
results_list[[ds]] <- datrans(count_mat = count_mat, labels = labels, perc_diffs = 0, n_ct_to_select = 0, reps = 20, n_cores = 1,
                                   methods = c(
                                     "counts",
                                     "freq",
                                     "arcsine_sqrt",
                                     "alr_randref",
                                     "alr_mincvref",
                                     "clr"
                                   ))
results_list[[ds]] <- results_list[[ds]] %>%
  group_by(method) %>%
  summarize(silhouette = mean(silhouette),
            modularity = mean(modularity),
            clustering = mean(clustering)) %>%
  ungroup()
results_list[[ds]]$dataset <- ds
```


#### Age (females cmvneg)

```{r}
seurat <- load_seurat_object("data/gongsharma_age_females_cmvneg.h5ad")
seurat$Sample <- seurat$specimen.specimenGuid
seurat$age <- as.factor(ifelse(seurat$sample.subjectAgeAtDraw < 50, "young", "old"))

label_condition <- "age"
low_res_ct_col <- "AIFI_L1"
hi_res_ct_col <- "AIFI_L3"

count_mat <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "GongSharma_age"
results_list[[ds]] <- datrans(count_mat = count_mat, labels = labels, perc_diffs = 0, n_ct_to_select = 0, reps = 20, n_cores = 1,
                                   methods = c(
                                     "counts",
                                     "freq",
                                     "arcsine_sqrt",
                                     "alr_randref",
                                     "alr_mincvref",
                                     "clr"
                                   ))
results_list[[ds]] <- results_list[[ds]] %>%
  group_by(method) %>%
  summarize(silhouette = mean(silhouette),
            modularity = mean(modularity),
            clustering = mean(clustering)) %>%
  ungroup()
results_list[[ds]]$dataset <- ds
```

## Plot results

```{r}
df_results <- Reduce(rbind, results_list)

df_results <- df_results %>%
  pivot_longer(
    cols = c(silhouette, modularity, clustering),
    names_to = "score_method",
    values_to = "values"
  ) %>%
  as.data.frame()

df_results_clustering <- df_results %>%
  filter(score_method == "clustering") %>%
  group_by(method) %>%
  summarize(mean = mean(values), sem = sd(values) / sqrt(length(values)))

df_results_clustering <- df_results_clustering %>%
  arrange(desc(mean))

df_results_clustering$method <- factor(df_results_clustering$method, levels = df_results_clustering$method)
df_results$method <- factor(df_results$method, levels = df_results_clustering$method)



# New facet label names for dose variable
score.labs <- c("Adjusted rand index", "Modularity score", "Silhouette score")
names(score.labs) <- sort(unique(df_results$score_method))

# New facet label names for supp variable
datas.labs <- c(
  "Gong & Sharma\nSubset: all\nSeparation by: CMV infection",
  "Gong & Sharma\nSubset: CMV negative females\nSeparation by: age",
  "Lee",
  "Stephenson",
  "Zhang")
names(datas.labs) <- sort(unique(df_results$dataset))



ggplot(df_results, aes(x = method, y = values)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(x = "",
       y = "Separation score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none") +
  facet_grid(score_method ~ dataset,
             scales = "free",
             labeller = labeller(score_method = score.labs, dataset = datas.labs))
  # facet_grid(scales = "free",
  #            rows = vars(score_method), cols = vars(dataset))
ggsave(file.path(path_plots, "transformations_real_datasets_detailed_barplot.pdf"),
       width = 8,
       height = 7)



df_results %>%
  group_by(score_method, method) %>%
  summarize(mean = mean(values), sem = sd(values) / sqrt(length(values))) %>%
  ungroup() %>%
  
  ggplot(aes(x = method, y = mean)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  # stat_summary(fun.y = mean, geom = "bar") +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=0.2, colour="black", alpha=0.9) +
  # geom_point(position = position_jitterdodge()) +
  labs(x = "", y = "Separation score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_grid(scales = "free",
             rows = vars(score_method),
             labeller = labeller(score_method = score.labs))


ggplot(df_results, aes(x = method, y = values)) +
  # geom_boxplot(outlier.shape = NA) +
  geom_point(aes(shape=dataset)) + 
  geom_line(aes(group=dataset, linetype=dataset), alpha = 1, color = "steelblue") +
  # geom_point(position = position_jitterdodge()) +
  labs(x = "", y = "Separation score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_grid(scales = "free",
             rows = vars(score_method),
             labeller = labeller(score_method = score.labs))

ggsave(file.path(path_plots, "transformations_real_datasets_summary_barplot_separatescores.pdf"),
       width = 5,
       height = 5)



df_results_clustering %>%
  ggplot(aes(x = method, y = mean)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  # stat_summary(fun.y = mean, geom = "bar") +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=0.2, colour="black", alpha=0.9) +
  # geom_point(position = position_jitterdodge()) +
  labs(x = "", y = "Adjusted Rand Index") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  NoLegend()


df_results_clustering <- df_results %>%
  filter(score_method == "clustering")

# Example assuming 'data' is your dataframe
anova_result <- aov(values ~ method, data = df_results_clustering)
summary(anova_result)
stat.test <- tukey_hsd(anova_result)
stat.test
stat.test$p.adj <- round(stat.test$p.adj, 3)
# stat.test <- stat.test[["method"]] %>% as.data.frame()
# 
# # Extract row names where p adj < 0.05
# significant_comparisons <- rownames(stat.test)[stat.test[["p adj"]] < 0.05]
# 
# # Initialize an empty list to store results
# my_comparisons <- list()
# 
# # Split and store each comparison in the list
# for (comparison in significant_comparisons) {
#   parts <- strsplit(comparison, "-")[[1]]
#   my_comparisons <- c(my_comparisons, list(parts))
# }

ggplot(df_results_clustering, aes(x = method, y = values)) +
  # geom_boxplot(outlier.shape = NA) +
  geom_point(aes(shape=dataset)) + 
  geom_line(aes(group=dataset, linetype=dataset), alpha = 1, color = "steelblue") +
  labs(x = "", y = "Adjusted Rand Index") +
  stat_compare_means(method = "anova", label.x.npc = 0.6, label.y.npc = 0.7) +
  # stat_compare_means(
  #   comparisons = my_comparisons,
  #   method = "t.test", 
  #   paired = F,
  #   p.adjust.method = "BH" #,
  #   # symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf), symbols = c("****", "***", "**", "*", "ns"))
  # ) +
  stat_pvalue_manual(stat.test, label = "p.adj", 
    y.position = c(max(df_results_clustering$values)+0.1, max(df_results_clustering$values)+0.2), hide.ns = TRUE) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

ggsave(file.path(path_plots, "transformations_real_datasets_summary_barplot.pdf"),
       width = 5,
       height = 3.5)

```

# Statistical comparison

```{r}
df_results_clustering <- df_results %>%
  filter(score_method == "clustering")

# Example assuming 'data' is your dataframe
anova_result <- aov(values ~ method, data = df_results_clustering)
summary(anova_result)

TukeyHSD(aov(df_results_clustering$values ~ df_results_clustering$method))
```


