---
title: "clr-transform - How to handle zeros"
author: "Christian Halter"
date: "`r format(Sys.Date(),'%e de %B, %Y')`"
output: 
  rmdformats::downcute:
    lightbox: true
    thumbnails: false
    self_contained: true
    gallery: true
    code_folding: show
  pkgdown:
    as_is: true
---

# Load libraries

```{r}
library(scooter)
library(Seurat)
library(dplyr)
library(ggplot2)
library(robCompositions)
library(zCompositions)
library(stringr)
library(tidyr)
source("functions.R")

# Set paths
path_plots <- path_plots <- file.path("~", "Dropbox", "CSI", "PAPERS", "ECODA", "plots")
```


## Test on real datasets

### Zhang et al. dataset

```{r}
ds_name <- "ZhangY_2022_34653365"
path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_output <- file.path(path_root, "output")
path_output_samples <- file.path(path_output, "samples")

obj.list <- read_objs(path_output_samples)

# Exclude samples that consist mainly of one cell type as outliers
samples_exclude <- c("Pre_P012_b", "Pre_P013_t")
obj.list <- obj.list[!names(obj.list) %in% samples_exclude]

samples_clearcut <- c()

for (i in names(obj.list)) {
  if (obj.list[[i]]@meta.data$Treatment[1] %in% c("Pre") &
      !(obj.list[[i]]@meta.data$Clinical.efficacy.[1] %in% c("-"))) {
    samples_clearcut <- c(samples_clearcut, i)
  }
}

metacols_to_keep <- c("Sample", "Tissue", "layer1", "layer2")

for (i in samples_clearcut) {
  print(i)
  
  obj <- obj.list[[i]]
  Idents(obj) <- "Sample"
  obj@meta.data <- obj@meta.data[colnames(obj@assays$RNA$counts), metacols_to_keep]

  if (i == samples_clearcut[1]) {
    seurat <- obj
  } else {
    seurat <- merge(seurat, obj)
  }
}

rm(obj.list); gc()

label_condition <- "Tissue"
low_res_ct_col <- "layer1"
hi_res_ct_col <- "layer2"


res_list <- list()

df <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "zhang"
df <- df %>% select_if(colSums(.) != 0) %>% mutate_all(as.numeric)
res_list[[paste0(ds, "_counts_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_0.5")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 0.5) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.0001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.0001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.01")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.01) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_10")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 10) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_asinsqrt")]] <- df %>% calc_perc_df() %>% mutate(across(everything(), ~ . / 100)) %>% sqrt() %>% asin() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_impRZilr")]] <- df %>% {impRZilr(.)[["x"]]} %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multLN_z0.9")]] <- df %>% calc_perc_df() %>% multLN(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.01")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.01, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_z0.9_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9, frac = 1) %>% clr() %>% calc_sep_score(labels)
```



### Stephenson et al. dataset


```{r}
# Set paths
ds_name <- "MitchelJ_2023_PrePrintTBD"

path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_output <- file.path(path_root, "output")

seurat <- readRDS(file.path(path_output, sprintf("%s_Stephenson_preprocessed.rds", ds_name)))

seurat <- subset(seurat, subset = Site == "Ncl")
seurat <- subset(seurat, subset = Status %in% c("Healthy", "Covid"))
seurat$Days_from_onset <- as.character(seurat$Days_from_onset)
seurat$Days_from_onset[seurat$Days_from_onset == "Healthy"] <- 0
seurat$Days_from_onset <- as.numeric(seurat$Days_from_onset)
seurat <- subset(seurat, subset = Days_from_onset < 10)

seurat$sample_id <- as.character(seurat$sample_id)
samples_exclude <- c("BGCV10_CV0198", "MH8919230")
samples_subset <- unique(seurat$sample_id[!seurat$sample_id %in% samples_exclude])
seurat <- subset(seurat, subset = sample_id %in% samples_subset)


label_condition <- "Status"
low_res_ct_col <- "initial_clustering"
hi_res_ct_col <- "full_clustering"


df <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "stephenson"
df <- df %>% select_if(colSums(.) != 0) %>% mutate_all(as.numeric)
res_list[[paste0(ds, "_counts_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_0.5")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 0.5) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.0001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.0001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.01")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.01) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_10")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 10) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_asinsqrt")]] <- df %>% calc_perc_df() %>% mutate(across(everything(), ~ . / 100)) %>% sqrt() %>% asin() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_impRZilr")]] <- df %>% {impRZilr(.)[["x"]]} %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multLN_z0.9")]] <- df %>% calc_perc_df() %>% multLN(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.01")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.01, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_z0.9_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9, frac = 1) %>% clr() %>% calc_sep_score(labels)
```


### Gong and Sharma et al. dataset (all CMV)


```{r}
# Set paths
ds_name <- "GongSharma_2024_PrePrintTBD"
path_root <- file.path("~", "Dropbox", "CSI", "Standardized_SingleCell_Datasets", ds_name)
path_output <- file.path(path_root, "output")

seurat <- load_seurat_object("gongsharma_all.h5ad")
seurat$Sample <- seurat$specimen.specimenGuid


label_condition <- "subject.cmv"
low_res_ct_col <- "AIFI_L1"
hi_res_ct_col <- "AIFI_L3"

df <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "gongsharma_allcmv"
df <- df %>% select_if(colSums(.) != 0) %>% mutate_all(as.numeric)
res_list[[paste0(ds, "_counts_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_0.5")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 0.5) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.0001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.0001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.01")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.01) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_10")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 10) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_asinsqrt")]] <- df %>% calc_perc_df() %>% mutate(across(everything(), ~ . / 100)) %>% sqrt() %>% asin() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_impRZilr")]] <- df %>% {impRZilr(.)[["x"]]} %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multLN_z0.9")]] <- df %>% calc_perc_df() %>% multLN(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.01")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.01, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_z0.9_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9, frac = 1) %>% clr() %>% calc_sep_score(labels)
```


## CMV (females)


```{r}
seurat <- load_seurat_object("gongsharma_cmv_females.h5ad")
seurat$Sample <- seurat$specimen.specimenGuid

label_condition <- "subject.cmv"
low_res_ct_col <- "AIFI_L1"
hi_res_ct_col <- "AIFI_L3"

df <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "gongsharma_cmvfemales"
df <- df %>% select_if(colSums(.) != 0) %>% mutate_all(as.numeric)
res_list[[paste0(ds, "_counts_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_0.5")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 0.5) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.0001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.0001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.01")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.01) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_10")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 10) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_asinsqrt")]] <- df %>% calc_perc_df() %>% mutate(across(everything(), ~ . / 100)) %>% sqrt() %>% asin() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_impRZilr")]] <- df %>% {impRZilr(.)[["x"]]} %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multLN_z0.9")]] <- df %>% calc_perc_df() %>% multLN(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.01")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.01, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_z0.9_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9, frac = 1) %>% clr() %>% calc_sep_score(labels)
```


## Age (females cmvneg)


```{r}
seurat <- load_seurat_object("gongsharma_age_females_cmvneg.h5ad")
seurat$Sample <- seurat$specimen.specimenGuid
seurat$age <- as.factor(ifelse(seurat$sample.subjectAgeAtDraw < 50, "young", "old"))

label_condition <- "age"
low_res_ct_col <- "AIFI_L1"
hi_res_ct_col <- "AIFI_L3"

df <- get_ct_comp_df_seurat(seurat, sample_col = "Sample", ct_col = hi_res_ct_col)
labels <- as.factor(get_labels(seurat, label_condition))

ds <- "gongsharma_agefemalescmvneg"
df <- df %>% select_if(colSums(.) != 0) %>% mutate_all(as.numeric)
res_list[[paste0(ds, "_counts_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_counts_all_0.5")]] <- df %>% impute_zeros(clr_zero_impute_method = "counts_all", clr_zero_impute_num = 0.5) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_zeros_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_zeros", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.0001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.0001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.001")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.001) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.01")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.01) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_0.1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 0.1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_1")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 1) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_perc_all_10")]] <- df %>% impute_zeros(clr_zero_impute_method = "percentage_all", clr_zero_impute_num = 10) %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_asinsqrt")]] <- df %>% calc_perc_df() %>% mutate(across(everything(), ~ . / 100)) %>% sqrt() %>% asin() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_impRZilr")]] <- df %>% {impRZilr(.)[["x"]]} %>% calc_perc_df() %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multLN_z0.9")]] <- df %>% calc_perc_df() %>% multLN(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.01")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.01, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_perc_all_1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(1, ncol(df)), z.warning = 1, frac = 1) %>% clr() %>% calc_sep_score(labels)
res_list[[paste0(ds, "_multRepl_z0.9_perc_all_0.1")]] <- df %>% calc_perc_df() %>% multRepl(label = 0, dl = rep(0.1, ncol(df)), z.warning = 0.9, frac = 1) %>% clr() %>% calc_sep_score(labels)
```


## Plot results

```{r}
df_results <- bind_rows(res_list, .id = "test_name") %>%
  mutate(test_name = as.character(test_name)) %>%
  dplyr::select(test_name, sil_score, mod_score, cluster_score)

strings <- df_results$test_name

# Remove the first part (split at "_") and the last part (split at "\\.")
first_parts <- sapply(str_split(strings, "_"), "[[", 1)
first_parts[grepl("gongsharma", first_parts)] <- paste0(first_parts[grepl("gongsharma", first_parts)], "_", sapply(str_split(strings[grepl("gongsharma", strings)], "_"), "[[", 2))
df_results$dataset <- first_parts

# Remove the first part (split at "_") and the last part (split at "\\.")
middle_parts <- str_remove(strings, "^[^_]*_")  # Remove everything up to and including the first "_"
middle_parts[grepl("cmv", middle_parts)] <- str_remove(middle_parts[grepl("cmv", middle_parts)], "^[^_]*_")  # Remove everything up to and including the first "_"
df_results$imputation_method <- middle_parts

df_results <- df_results %>%
  pivot_longer(
    cols = c(sil_score, mod_score, cluster_score),
    names_to = "score_method",
    values_to = "values"
  ) %>%
  as.data.frame()

ggplot(df_results, aes(x = imputation_method, y = values)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(x = "Imputation method",
       y = "Separation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none") +
  facet_grid(scales = "free",
             rows = vars(score_method), cols = vars(dataset))
ggsave(file.path(path_plots, "zero_imputation_real_datasets_detailed_barplot.pdf"),
       width = 12,
       height = 7)




df_results %>%
  group_by(score_method, imputation_method) %>%
  summarize(mean = mean(values), sem = sd(values) / sqrt(length(values))) %>%
  ungroup() %>%
  
  ggplot(aes(x = imputation_method, y = mean)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  # stat_summary(fun.y = mean, geom = "bar") +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=0.2, colour="black", alpha=0.9) +
  # geom_point(position = position_jitterdodge()) +
  labs(x = "", y = "Separation score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_grid(scales = "free",
             rows = vars(score_method))

ggsave(file.path(path_plots, "zero_imputation_real_datasets_summary_barplot_separatescores.pdf"),
       width = 5,
       height = 7)


df_results %>%
  filter(score_method == "cluster_score") %>%
  group_by(imputation_method) %>%
  summarise(mean = mean(values), sem = sd(values) / sqrt(length(values))) %>%
  ggplot(aes(x = imputation_method, y = mean)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  # stat_summary(fun.y = mean, geom = "bar") +
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=0.2, colour="black", alpha=0.9) +
  # geom_point(position = position_jitterdodge()) +
  labs(x = "", y = "Adjusted Rand Index") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  NoLegend()
ggsave(file.path(path_plots, "zero_imputation_real_datasets_summary_barplot.pdf"),
       width = 5,
       height = 4)


library(rstatix)

df_results_cluster <- df_results %>% filter(score_method == "cluster_score")

outlier <- df_results_cluster %>%
  group_by(imputation_method) %>%
  rstatix::identify_outliers(values)
data.frame(outlier)

normality <- df_results_cluster %>%
  group_by(imputation_method) %>%
  rstatix::shapiro_test(values)
data.frame(normality)
cat(paste("All groups normally ditributed?", all(normality$p > 0.05),
            "\nNot normally distributed:", normality$imputation_method[normality$p <= 0.05]))

res <- rstatix::anova_test(data = df_results_cluster, dv = values, wid = dataset, within = imputation_method) 
rstatix::get_anova_table(res)

pair <- df_results_cluster %>%
  rstatix::pairwise_t_test(values~imputation_method, paired=TRUE, p.adjust.method = "BH" ) 
data.frame(pair) 
```

```{r fig.height=5, fig.width=16}
df_plot <- data.frame(values = unlist(res_list),
                      dataset = dataset,
                      imputation_method = imputation_method,
                      score = sapply(str_split(names(unlist(res_list)), "\\."), function(x) x[length(x)]))

ggplot(df_plot, aes(x = imputation_method, y = values)) +
  geom_bar(stat = "identity", position = "stack") +
  # labs(title = "Grouped Bar Plot",
  #      x = "Dataset",
  #      y = "Values",
  #      fill = "Score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "none") +
  facet_grid(~dataset,
             space  = "free",
             scales = "free")

ggplot(df_plot, aes(x = imputation_method, y = values, group = score, color = score)) +
  geom_line() +
  geom_point(aes(shape=score)) +
  # labs(title = "Grouped Bar Plot",
  #      x = "Dataset",
  #      y = "Values",
  #      fill = "Score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_grid(~dataset,
             space  = "free",
             scales = "free")

df_plot <- data.frame(values = unlist(res_list),
                      dataset = dataset,
                      imputation_method = middle_parts,
                      score = sapply(str_split(names(unlist(res_list)), "\\."), function(x) x[length(x)]))
df_plot$imputation_method <- gsub("\\.sil_score|\\.mod_score", "", df_plot$imputation_method)
df_plot$ds_row <- factor(ifelse(grepl(pattern = "gongsharma", df_plot$dataset), 1, 2))
ggplot(df_plot, aes(x = imputation_method, y = values, fill = score)) +
  geom_bar(stat = "identity", position = position_dodge(), width = 0.7) +
  # labs(title = "Grouped Bar Plot",
  #      x = "Dataset",
  #      y = "Values",
  #      fill = "Score") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "none") +
  facet_grid(scales = "free",
             rows = vars(score), cols = vars(dataset))
ggsave(file.path(path_plots, "zero_imputation_real_datasets_detailed_barplot.pdf"),
       width = 12,
       height = 7)
```

