---
title: "clr-transform - How to handle zeros"
author: "Christian Halter"
date: "`r format(Sys.Date(),'%e de %B, %Y')`"
output: 
  rmdformats::downcute:
    lightbox: true
    thumbnails: false
    self_contained: true
    gallery: true
    code_folding: show
  pkgdown:
    as_is: true
---

# Load libraries

```{r}
library(dplyr)
library(ggplot2)
source("functions.R")

# Set paths
path_plots <- path_plots <- file.path("~", "Dropbox", "CSI", "PAPERS", "ECODA", "plots")
```


# Synthetic data

## Counts vs freq vs clr

Why not use counts?

```{r fig.height=3, fig.width=5}
library(simstudy)
library(factoextra)
library(easyCODA)

# Define group
def <- defData(varname = "group", formula = "1;1;1", dist = "trtAssign")
def <- defRepeat(def, 2, "ct_const_", formula = "10", variance = 0.1,
    dist = "normal")
def <- defRepeat(def, 1, "ct_var1_", formula = "10 * group", variance = 0.1,
    dist = "normal")

df <- genData(9, def)

# Sort by group
df <- df[order(df$group), ]
# df$sample_id <- NULL
df$id <- 1:dim(df)[1]

df[c(2,5,8),3:5] <- df[c(2,5,8),3:5] * 10
df[c(3,6,9),3:5] <- df[c(3,6,9),3:5] * 100

df[,3:5] <- round(df[,3:5])

habillage = factor(df$group)

df_counts <- df
df_long <- reshape2::melt(df_counts, id = c("id", "group"))
ggplot(df_long, aes(x = id, y = value, fill=variable)) +
  geom_bar(position="dodge", stat="identity") +
  facet_wrap(. ~ group, scales = "free_x") +
  xlab("Sample") +
  ylab("Cell counts")
# calc_sil(feat_mat = df_counts[, 3:5],
#          labels = df_counts[, 2])
fviz_pca(prcomp(df_counts[,3:5]),
         habillage = habillage,
         invisible = c("var", "quali"),
         # label = "none",
         mean.point = FALSE)

df_perc <- df
df_perc[,3:5] <- df_perc[,3:5] / rowSums(df_perc[,3:5]) * 100
df_perc <- as.data.frame(df_perc)
df_long <- reshape2::melt(df_perc, id = c("id", "group"))
ggplot(df_long, aes(x = id, y = value, fill=variable)) +
  geom_bar(position="dodge", stat="identity") +
  facet_wrap(. ~ group, scales = "free_x") +
  xlab("Sample") +
  ylab("Relative abundance (%)")
fviz_pca(prcomp(df_perc[,3:5]),
         habillage = habillage,
         # invisible = c("var", "quali"),
         # label = "none",
         mean.point = FALSE)

df_clr <- df_perc
df_clr[,3:5] <- Hotelling::clr(df_clr[,3:5])
df_long <- reshape2::melt(df_clr, id = c("id", "group"))
ggplot(df_long, aes(x = id, y = value, fill=variable)) +
  geom_bar(position="dodge", stat="identity") +
  facet_wrap(. ~ group, scales = "free_x") +
  xlab("Sample") +
  ylab("Relative abundance (clr-transformed)")
fviz_pca(prcomp(df_clr[,3:5]),
         habillage = habillage,
         # invisible = c("var", "quali"),
         # label = "none",
         mean.point = FALSE)
```

## freq vs clr

Why not use freq?

```{r}
library(simstudy)
library(factoextra)
library(easyCODA)

# Define group
def <- defData(varname = "group", formula = "1;1;1", dist = "trtAssign")
def <- defRepeat(def, 1, "ct_const_low_", formula = "3", variance = 0,
    dist = "normal")
def <- defRepeat(def, 3, "ct_const_medium_", formula = "10", variance = 5,
    dist = "normal")
def <- defRepeat(def, 3, "ct_const_high_", formula = "100", variance = 5,
    dist = "normal")
def <- defRepeat(def, 1, "ct_var1_", formula = "1 * group", variance = 0,
    dist = "normal")

df <- genData(9, def)

# Sort by group
df <- df[order(df$group), ]
# df$id <- NULL
df$id <- 1:dim(df)[1]

# df[c(2,5,8),3:6] <- df[c(2,5,8),3:6] * 10
# df[c(3,6,9),3:6] <- df[c(3,6,9),3:6] * 100

df_cols <- dim(df)[2]

df[,3:df_cols] <- round(df[,3:df_cols])

habillage = factor(df$group)

df_perc <- df
df_perc[,3:df_cols] <- df_perc[,3:df_cols] / rowSums(df_perc[,3:df_cols]) * 100
df_perc <- as.data.frame(df_perc)
df_long <- reshape2::melt(df_perc, id = c("id", "group"))
ggplot(df_long, aes(x = id, y = value, fill=variable)) +
  geom_bar(position="dodge", stat="identity") +
  xlab("Sample") +
  ylab("Relative abundance (%)")
fviz_pca(prcomp(df_perc[,3:df_cols]),
         habillage = habillage,
         # invisible = c("var", "quali"),
         # label = "none",
         mean.point = FALSE)

df_clr <- df_perc
df_clr[,3:df_cols] <- Hotelling::clr(df_clr[,3:df_cols])
df_long <- reshape2::melt(df_clr, id = c("id", "group"))
ggplot(df_long, aes(x = id, y = value, fill=variable)) +
  geom_bar(position="dodge", stat="identity") +
  xlab("Sample") +
  ylab("Relative abundance (clr-transformed)")
fviz_pca(prcomp(df_clr[,3:df_cols]),
         habillage = habillage,
         # invisible = c("var", "quali"),
         # label = "none",
         mean.point = FALSE)
```

## +1 count, +1%, KNN, model

Why not use freq?

```{r}
library(simstudy)
library(factoextra)
library(easyCODA)

# Define group
def <- defData(varname = "group", formula = "1;1;1", dist = "trtAssign")
def <- defRepeat(def, 1, "ct_zero_imputed", formula = "3", variance = 0,
    dist = "normal")
def <- defRepeat(def, 1, "ct_10_", formula = "10", variance = 0,
    dist = "normal")
def <- defRepeat(def, 1, "ct_const_high_", formula = "100", variance = 0,
    dist = "normal")
def <- defRepeat(def, 1, "ct_var1_", formula = "1 * group", variance = 0,
    dist = "normal")

df <- genData(9, def)

# Sort by group
df <- df[order(df$group), ]
# df$id <- NULL
df$id <- 1:dim(df)[1]

# df[c(2,5,8),3:6] <- df[c(2,5,8),3:6] * 10
# df[c(3,6,9),3:6] <- df[c(3,6,9),3:6] * 100

df_cols <- dim(df)[2]

df[,3:df_cols] <- round(df[,3:df_cols])

habillage = factor(df$group)

df_perc <- df
df_perc[,3:df_cols] <- df_perc[,3:df_cols] / rowSums(df_perc[,3:df_cols]) * 100
df_perc <- as.data.frame(df_perc)
df_long <- reshape2::melt(df_perc, id = c("id", "group"))
ggplot(df_long, aes(x = id, y = value, fill=variable)) +
  geom_bar(position="dodge", stat="identity") +
  xlab("Sample") +
  ylab("Relative abundance (%)")
fviz_pca(prcomp(df_perc[,3:df_cols]),
         habillage = habillage,
         # invisible = c("var", "quali"),
         # label = "none",
         mean.point = FALSE)

df_clr <- df_perc
df_clr[,3:df_cols] <- Hotelling::clr(df_clr[,3:df_cols])
df_long <- reshape2::melt(df_clr, id = c("id", "group"))
ggplot(df_long, aes(x = id, y = value, fill=variable)) +
  geom_bar(position="dodge", stat="identity") +
  xlab("Sample") +
  ylab("Relative abundance (clr-transformed)")
fviz_pca(prcomp(df_clr[,3:df_cols]),
         habillage = habillage,
         # invisible = c("var", "quali"),
         # label = "none",
         mean.point = FALSE)
```



show example why ratios matter

rel abu vs clr (real-world data)(clustering e.g. tissue)
rel abu vs clr (real-world data)(clustering e.g. CD8.Tex)